server:
  port: ${port:8001}
spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
  application:
    name: provide

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #发送心跳时间间隔
    lease-renewal-interval-in-seconds: 5
    #没发送心跳继续等待时间，如果还没发送，服务失效
    lease-expiration-duration-in-seconds: 5